### ISSUE TITLE
Add endpoint to output a project in a dialect

### ISSUE THREAD

**Issue by TitusKirch** [cntitanium/babylon#66]
As an example:
- WSC
- Minecraft (propertie files)

Output as a zip file

**Comment by steve-hb** [comment]
Clarification: We should generate a zip file which can easily be dropped in a repository by the user.
In case of Minecraft the format would be multiple .properties files corresponding to the languages they contain.
Example: de_De.properties for German used in Germany, en_US.properties for American English, en_UK.properties for British English etc.
