### ISSUE TITLE
Add PR templates

### ISSUE THREAD

**Issue by Sofaklient** [cntitanium/babylon#8]

**Comment by Sofaklient** [comment]
I suggest using the experimental GitHub Discussions for questions and suggestions, leaving the issues solely to organize and document the development process.

Thus, instead of using issue templates, we could link the according discussions forums directly as depicted below.

![Example illustrating the use of external links](https://user-images.githubusercontent.com/20745548/114747664-5d68e780-9d51-11eb-98ad-92cc2e98d2bf.png)

It might still make sense to add a bug report template. What do you think?

**Comment by TitusKirch** [comment]
Sounds good

**Comment by Sofaklient** [comment]
Comments are displaced and belong to #7 instead.
