### ISSUE TITLE
Finish (basic) OpenAPI endpoints

### ISSUE THREAD

**Issue by steve-hb** [cntitanium/babylon#81]
Finish all the needed CRUD endpoints in our OpenAPI doc.
Also mind that we shouldn't delete things, instead we should hide them from users using flags - except an admin REALLY wants to delete it (maybe only hide them by default?).

- Projects
  - Create project
  - Delete project
  - Update project name
- Phrase
  - Create phrase
  - Delete phrase
  - Add/Remove translation
  - Add comment
  - Get phrase by key
  - Get phrases by project
- Translation
  - Create translation
  - Delete translation
  - Update template
  - Update proposal id (new proposal gets accepted)
  - Add comment
- Proposal
  - Create proposal
  - Delete proposal
  - Update status
  - Update template (history -> Event Sourcing!)
  - Add comment
  - Get proposal by proposalId
  - Get proposals by projectId
  - Get proposals by author
  - Get proposals by key
  - Get proposals by language
- (New) Comment
  - Create comment
    - author
    - createdAt
    - content
    - reactions (?)
  - Delete comment
  - Update comment (history!)

**Comment by Sofaklient** [comment]
**Add a `/alpha-v1/` at the start of _every single route_ to ensure us being able to rework the whole API at some point, if needed.**

**Generally, add READ endpoints to `Project`(_s, see below_), Translation (several [bulk] options, just like in `Proposal`), `Comment`.**

**Also, add User endpoints (we'll use SSO for now!).**

**All Strings, such as project names or descriptions, should be translatable.** Don't add them to the stack of `Phrase`s though, this kind of thing only needs to be editable by staff. Should we allow multi-language `Comment`s, too?

Everything should be commentable, thus we need to add according endpoints on every schema endpoint where there isn't one already. I think I didn't miss out on any, but just add one anyway if I did. Will `Comment`s be saved within the document they refer to, or are they saved globally? Both would have specific advantages and disadvantages, such as possibilities to reply to comments (needs further discussion) or one to loop through all comments quickly.

To provide a better overview, we should either start modelling the schemas in this issue, too, or move to a PR draft. As there way to distinguish cleanly between the two right now, this might become quite a mess. Apologies in advance.

- Projects
  - _Switch to singular form: `Project`_
  - **Points raised above list**
  - Add a `projectStatus` (enum `ProjectStatus`, e.g. `DRAFT`, `PUBLISHED`, `LOCKED`, `HIDDEN`?) and corresponding RU routes
  - Add a project description and corresponding (C)RU(D) routes
  - Add CREATE endpoint for comments
- Phrase
  - Add possibility to bulk add phrases and their corresponding original translations? Clients might exceed API limits by implementing this via UI
  - Edit "Add/Remove Translation": Add separate routes
  - Add a `phraseType` (preferably not an Enum, but an own collection (or a set of possible values with respective renderers/resolvers on both frontend and backend), to provide applicability to more use-cases). `PhraseType`s should make distinction between colored minecraft messages (`&c{{ killer }} &fkilled &c{{ victim }}&f!`) and formatted web messages (`<b>{{ killer }}</b> killed <b>{{ victim }}</b>!`) possible. The logic behind this can obviously be implemented at a later point, but it's a nice-to-have as we develop the API now anyway, as we strive for decent usability even at our first alpha release.
- Translation
  - **Points raised above list**
- Proposal
  - Add possibility to up-/downvote other peoples' proposals to enhance the translation process (would the history be queryable quickly enough to ensure a seemless user experience without allowing multiple up-/downvotes by a single user?)
  - ^Add according ways to sort proposals to a given key by their popularity
- Comment
  - **Points raised above list**

**Comment by Sofaklient** [comment]
We need to investigate the degree in which an existing generated OpenAPI codebase can be modified without breaking the existent code. Depending on our findings, we could leave out some of my points or the need for further planning might arise.

**Comment by TitusKirch** [comment]
@Sofaklient has already mentioned the things I was missing. However, I would not limit the projectStatus to an enum. They should be freely definable by the admins.

**Comment by Sofaklient** [comment]
> 
> 
> @Sofaklient has already mentioned the things I was missing. However, I would not limit the projectStatus to an enum. They should be freely definable by the admins.

If we do so, we might as well just add the possibility to open/close projects and to hide them from the public if need be. Freely definable statuses could be implemented as labels at a later stage.

**Comment by steve-hb** [comment]
I'm taking over.

**Comment by steve-hb** [comment]
I'll postpone bulk operations and proposals etc.
The current state of #105 should be enough to create, update and get projects and phrases on a basic level.
The frontend team needs a basic backend, we'll introduce more functionality with the future MRs.
